theme: jekyll-theme-slate

permalink: /posts/:title

markdown: kramdown

gems:
• jekyll-sitemap

title: 'rudegay'

Page title: 'intro'

url: ' https://b0rnfly.github.io ' baseurl: '/'

description: A fantastic blog that is fantastic.

twitter: holman