permalink: /posts/:title

markdown: kramdown

#site info

title: 'rudegay'

Page title: 'intro'

url: ' https://b0rnfly.github.io ' baseurl: '/'

description: A fantastic blog that is fantastic.

twitter: holman