theme: jekyll-theme-slate

permalink: /posts/:title

markdown: kramdown

gems:

- jekyll-sitemap

site title: 'rudegay'

url: 'https://b0rnfly.github.io'
baseurl: '/'

description: A fantastic blog that is fantastic.

twitter: holman


